//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Data/InputActions/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""FPV"",
            ""id"": ""85262d87-3cda-470a-a018-1482aea3fb96"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""9a0a29d1-e465-42d4-9b10-00a2f0157e17"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""b5354137-79ca-4c0c-9f35-a9b5f9902918"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""990d2ea9-44b4-49d5-8414-9c3e5f1be62b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCamera"",
                    ""type"": ""Button"",
                    ""id"": ""99e78472-ef1f-4a7f-91ad-91c1fe4e6260"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""3bf926aa-a224-472f-9ad8-b7f04588d1cd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d7b7df75-8de8-46ce-9211-7dfa65845798"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67414e4d-eb6b-40df-b12e-da827f0e32f8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13d36c30-9382-4f8c-a464-e825045f935d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64453b48-f13c-41bd-aeff-508ab13a9dde"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2c62f5af-40d9-4267-9c29-f2ac1c5dd3cb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3aa5a0f2-3d9e-47ab-8fb0-7f7d4cbf509b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""512dbb58-5ed7-44bb-9bce-537597f1dc90"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3077c526-540e-4f6e-baea-e4f653d6b01e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bc94192c-7ecf-4b47-92fa-7e253a2b1024"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Top-Down"",
            ""id"": ""769e8037-b798-435a-9e1d-afde285c0a7b"",
            ""actions"": [
                {
                    ""name"": ""ScreenEdgePanning"",
                    ""type"": ""Value"",
                    ""id"": ""42149a0f-314e-4e42-b309-60a2008d51dd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""KeyboardCameraMovement"",
                    ""type"": ""Value"",
                    ""id"": ""7bd73732-7b3c-41b8-9494-ef496644ee10"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClickAndDrag"",
                    ""type"": ""Button"",
                    ""id"": ""29f399b9-f17d-4c25-ab35-ceb884774b63"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomCamera"",
                    ""type"": ""Value"",
                    ""id"": ""6c077486-98db-4dbf-b085-228ec429aa8e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""b6a00bf1-82a5-4add-a045-cc250d387aae"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCamera"",
                    ""type"": ""Button"",
                    ""id"": ""f0a3cafc-2418-4885-a70a-af4882de117c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""a22b4709-551e-4840-a306-1bc6131f63c5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fc0ec935-b726-4dee-9b55-95260a6bcb4e"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""968bc627-58cd-42e6-8dfa-cf203c7aff30"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afc6d4e9-8d80-4dc1-89c4-26a59fbdc5fb"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c83bd80c-886b-4eb2-b8cb-57ac1cfc25bb"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScreenEdgePanning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a27e85c4-745b-4f89-83f4-f2edd1bac4c1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardCameraMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3046f72f-2b30-4a4d-a8d1-b7ca0119b466"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardCameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7ecf46e4-20d7-4a51-866c-c409486b090e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardCameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b4ef7ea7-cb7c-48d2-8641-28ce0106fe3a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardCameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b4f1733d-6d3c-4247-a476-63f7037c7863"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardCameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c840c0d2-eee8-40be-a61d-af1717ec742c"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickAndDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab5f341e-8257-42f1-ad4f-7e02047a2172"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Isometric"",
            ""id"": ""9e2e56e4-eb88-45b1-b3bd-1a160902f751"",
            ""actions"": [
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Value"",
                    ""id"": ""b6ea6928-f18f-4bc1-a6ce-c0fcdcf13ec9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""2e6b0af4-1b11-4cc4-8495-30271496bb72"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCamera"",
                    ""type"": ""Button"",
                    ""id"": ""a96743d7-b5bf-4e14-9a99-88c73b0f9ba6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""84e5d877-75cf-49ea-9142-ef905c4a8238"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""030b77c3-9dad-4c5d-bf9a-93467561e4c8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d8180b37-987b-4a74-8b0f-6897148b6d02"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12da11d6-6c20-4246-9b4e-4b3a1b328fc4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35be2daf-3671-477e-88c1-7d63acc7e65a"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9036dd3-ae9f-4c19-99de-ca39583d7a80"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""cdd4c16e-3d84-48c9-abe0-8395fab25780"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b5ff1451-9ce6-4f60-b600-03e31a17eed3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3d1bac7d-9dd5-492e-b6ec-4091aba6b555"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e996bc02-40e7-405e-8cea-08286e364085"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6e7a0b55-eb39-4dc1-8d72-6066fdc3294a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""DefNumbers"",
            ""id"": ""537fa1d5-ab45-4649-8825-b37500a6c53f"",
            ""actions"": [
                {
                    ""name"": ""One"",
                    ""type"": ""Button"",
                    ""id"": ""1bd3b47c-c0b4-4467-aa68-a17924fda505"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two"",
                    ""type"": ""Button"",
                    ""id"": ""f92570db-5272-4209-9dc7-0bfab4c17eca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three"",
                    ""type"": ""Button"",
                    ""id"": ""33966254-4f54-4785-a828-403bc721f6fc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Four"",
                    ""type"": ""Button"",
                    ""id"": ""a688737b-4aa7-4d05-b784-bdaf5ccba85d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Five"",
                    ""type"": ""Button"",
                    ""id"": ""99b65c48-f718-42a6-9725-145dfd72091a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Six"",
                    ""type"": ""Button"",
                    ""id"": ""53f16f61-91e2-4386-b93f-ffc2a55bb82d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Seven"",
                    ""type"": ""Button"",
                    ""id"": ""9c1fb380-e5b8-4385-bc48-c925e0c00c80"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eight"",
                    ""type"": ""Button"",
                    ""id"": ""f984b44c-de6b-43d4-a937-a02d527d7903"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Nine"",
                    ""type"": ""Button"",
                    ""id"": ""d4008b1f-ea7b-4c73-b1e3-2c47db3857a6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zero"",
                    ""type"": ""Button"",
                    ""id"": ""cc93fa49-cfef-45b7-ad4b-83d139930daf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6170deb2-f369-4e52-b5af-d4bf4b6a4a89"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""One"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2adaf724-d143-4e34-b791-f02a7874fa0b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Two"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""190de8b8-660b-4325-b040-b6221742f9d8"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Three"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e97f969b-14d3-4b12-bf8b-5f7434086a17"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Four"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd1d136e-e83e-4e86-adf3-4aa0a246b13c"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Five"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6e82b22-d435-4ad1-ba50-629b36693061"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Six"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f98f2fc7-d6cf-4e56-bf32-a35ce4d56718"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Seven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3badc498-e85e-43aa-a788-93f78c2b9ed9"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Eight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58105739-1cf8-4bdf-913f-395004ccfcc7"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caca9ede-571b-4f67-820b-493e467a6878"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OptionsNumbers"",
            ""id"": ""da73e702-d416-4766-b3ba-b5ed2ba727e6"",
            ""actions"": [
                {
                    ""name"": ""One"",
                    ""type"": ""Button"",
                    ""id"": ""7c104315-b642-4827-8f86-905bd232be8d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two"",
                    ""type"": ""Button"",
                    ""id"": ""67eddd05-812e-437c-a57a-9f199406e2a3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three"",
                    ""type"": ""Button"",
                    ""id"": ""e3637755-4d7c-4bb0-ad63-bc19ff67e0d4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Four"",
                    ""type"": ""Button"",
                    ""id"": ""aacde1d1-361b-4118-8039-53363743a8f1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Five"",
                    ""type"": ""Button"",
                    ""id"": ""ac9421a9-df5f-4eb2-a24a-982938fc4604"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Six"",
                    ""type"": ""Button"",
                    ""id"": ""738d4baa-3c65-4f42-a59d-eb1c166fe78a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Seven"",
                    ""type"": ""Button"",
                    ""id"": ""36e5200d-133b-4412-b07b-b0f061d99428"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eight"",
                    ""type"": ""Button"",
                    ""id"": ""634a653a-114e-46de-b863-8366c3a7b288"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Nine"",
                    ""type"": ""Button"",
                    ""id"": ""ce29d8b1-694f-49a7-8f33-c230133faf4b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zero"",
                    ""type"": ""Button"",
                    ""id"": ""cfb87198-0ed0-417b-a7ad-974c28a0f4a7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2c894944-4522-4c87-a7c0-32f87232f93d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""One"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be4d3c46-716e-42fd-8170-8c1ed2a5d759"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Two"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12ae7582-1d38-474f-bb18-5506b9b4051d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Three"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd1ca249-8ddd-46b8-9ae0-e2d3a9215b34"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Four"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""293d561e-3266-43d5-8dcc-ac4907d2b5be"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Five"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95319bf9-db95-4879-8ba3-1c088c6e7237"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Six"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""416e22ad-d506-4985-9289-28c7a4a88f4f"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Seven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b34b41f-5329-4c75-94f8-4277735d37c3"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Eight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ec0892c-39dd-4509-9eda-240124673746"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ba63d56-908d-4d72-b481-807ed598b83b"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // FPV
        m_FPV = asset.FindActionMap("FPV", throwIfNotFound: true);
        m_FPV_Movement = m_FPV.FindAction("Movement", throwIfNotFound: true);
        m_FPV_RotateCamera = m_FPV.FindAction("RotateCamera", throwIfNotFound: true);
        m_FPV_Interaction = m_FPV.FindAction("Interaction", throwIfNotFound: true);
        m_FPV_SwitchCamera = m_FPV.FindAction("SwitchCamera", throwIfNotFound: true);
        m_FPV_SwitchCharacter = m_FPV.FindAction("SwitchCharacter", throwIfNotFound: true);
        // Top-Down
        m_TopDown = asset.FindActionMap("Top-Down", throwIfNotFound: true);
        m_TopDown_ScreenEdgePanning = m_TopDown.FindAction("ScreenEdgePanning", throwIfNotFound: true);
        m_TopDown_KeyboardCameraMovement = m_TopDown.FindAction("KeyboardCameraMovement", throwIfNotFound: true);
        m_TopDown_ClickAndDrag = m_TopDown.FindAction("ClickAndDrag", throwIfNotFound: true);
        m_TopDown_ZoomCamera = m_TopDown.FindAction("ZoomCamera", throwIfNotFound: true);
        m_TopDown_Interaction = m_TopDown.FindAction("Interaction", throwIfNotFound: true);
        m_TopDown_SwitchCamera = m_TopDown.FindAction("SwitchCamera", throwIfNotFound: true);
        m_TopDown_SwitchCharacter = m_TopDown.FindAction("SwitchCharacter", throwIfNotFound: true);
        // Isometric
        m_Isometric = asset.FindActionMap("Isometric", throwIfNotFound: true);
        m_Isometric_Mouse = m_Isometric.FindAction("Mouse", throwIfNotFound: true);
        m_Isometric_Interaction = m_Isometric.FindAction("Interaction", throwIfNotFound: true);
        m_Isometric_SwitchCamera = m_Isometric.FindAction("SwitchCamera", throwIfNotFound: true);
        m_Isometric_SwitchCharacter = m_Isometric.FindAction("SwitchCharacter", throwIfNotFound: true);
        m_Isometric_Movement = m_Isometric.FindAction("Movement", throwIfNotFound: true);
        // DefNumbers
        m_DefNumbers = asset.FindActionMap("DefNumbers", throwIfNotFound: true);
        m_DefNumbers_One = m_DefNumbers.FindAction("One", throwIfNotFound: true);
        m_DefNumbers_Two = m_DefNumbers.FindAction("Two", throwIfNotFound: true);
        m_DefNumbers_Three = m_DefNumbers.FindAction("Three", throwIfNotFound: true);
        m_DefNumbers_Four = m_DefNumbers.FindAction("Four", throwIfNotFound: true);
        m_DefNumbers_Five = m_DefNumbers.FindAction("Five", throwIfNotFound: true);
        m_DefNumbers_Six = m_DefNumbers.FindAction("Six", throwIfNotFound: true);
        m_DefNumbers_Seven = m_DefNumbers.FindAction("Seven", throwIfNotFound: true);
        m_DefNumbers_Eight = m_DefNumbers.FindAction("Eight", throwIfNotFound: true);
        m_DefNumbers_Nine = m_DefNumbers.FindAction("Nine", throwIfNotFound: true);
        m_DefNumbers_Zero = m_DefNumbers.FindAction("Zero", throwIfNotFound: true);
        // OptionsNumbers
        m_OptionsNumbers = asset.FindActionMap("OptionsNumbers", throwIfNotFound: true);
        m_OptionsNumbers_One = m_OptionsNumbers.FindAction("One", throwIfNotFound: true);
        m_OptionsNumbers_Two = m_OptionsNumbers.FindAction("Two", throwIfNotFound: true);
        m_OptionsNumbers_Three = m_OptionsNumbers.FindAction("Three", throwIfNotFound: true);
        m_OptionsNumbers_Four = m_OptionsNumbers.FindAction("Four", throwIfNotFound: true);
        m_OptionsNumbers_Five = m_OptionsNumbers.FindAction("Five", throwIfNotFound: true);
        m_OptionsNumbers_Six = m_OptionsNumbers.FindAction("Six", throwIfNotFound: true);
        m_OptionsNumbers_Seven = m_OptionsNumbers.FindAction("Seven", throwIfNotFound: true);
        m_OptionsNumbers_Eight = m_OptionsNumbers.FindAction("Eight", throwIfNotFound: true);
        m_OptionsNumbers_Nine = m_OptionsNumbers.FindAction("Nine", throwIfNotFound: true);
        m_OptionsNumbers_Zero = m_OptionsNumbers.FindAction("Zero", throwIfNotFound: true);
    }

    ~@InputActions()
    {
        UnityEngine.Debug.Assert(!m_FPV.enabled, "This will cause a leak and performance issues, InputActions.FPV.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_TopDown.enabled, "This will cause a leak and performance issues, InputActions.TopDown.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Isometric.enabled, "This will cause a leak and performance issues, InputActions.Isometric.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_DefNumbers.enabled, "This will cause a leak and performance issues, InputActions.DefNumbers.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_OptionsNumbers.enabled, "This will cause a leak and performance issues, InputActions.OptionsNumbers.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FPV
    private readonly InputActionMap m_FPV;
    private List<IFPVActions> m_FPVActionsCallbackInterfaces = new List<IFPVActions>();
    private readonly InputAction m_FPV_Movement;
    private readonly InputAction m_FPV_RotateCamera;
    private readonly InputAction m_FPV_Interaction;
    private readonly InputAction m_FPV_SwitchCamera;
    private readonly InputAction m_FPV_SwitchCharacter;
    public struct FPVActions
    {
        private @InputActions m_Wrapper;
        public FPVActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_FPV_Movement;
        public InputAction @RotateCamera => m_Wrapper.m_FPV_RotateCamera;
        public InputAction @Interaction => m_Wrapper.m_FPV_Interaction;
        public InputAction @SwitchCamera => m_Wrapper.m_FPV_SwitchCamera;
        public InputAction @SwitchCharacter => m_Wrapper.m_FPV_SwitchCharacter;
        public InputActionMap Get() { return m_Wrapper.m_FPV; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FPVActions set) { return set.Get(); }
        public void AddCallbacks(IFPVActions instance)
        {
            if (instance == null || m_Wrapper.m_FPVActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FPVActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @RotateCamera.started += instance.OnRotateCamera;
            @RotateCamera.performed += instance.OnRotateCamera;
            @RotateCamera.canceled += instance.OnRotateCamera;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @SwitchCamera.started += instance.OnSwitchCamera;
            @SwitchCamera.performed += instance.OnSwitchCamera;
            @SwitchCamera.canceled += instance.OnSwitchCamera;
            @SwitchCharacter.started += instance.OnSwitchCharacter;
            @SwitchCharacter.performed += instance.OnSwitchCharacter;
            @SwitchCharacter.canceled += instance.OnSwitchCharacter;
        }

        private void UnregisterCallbacks(IFPVActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @RotateCamera.started -= instance.OnRotateCamera;
            @RotateCamera.performed -= instance.OnRotateCamera;
            @RotateCamera.canceled -= instance.OnRotateCamera;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @SwitchCamera.started -= instance.OnSwitchCamera;
            @SwitchCamera.performed -= instance.OnSwitchCamera;
            @SwitchCamera.canceled -= instance.OnSwitchCamera;
            @SwitchCharacter.started -= instance.OnSwitchCharacter;
            @SwitchCharacter.performed -= instance.OnSwitchCharacter;
            @SwitchCharacter.canceled -= instance.OnSwitchCharacter;
        }

        public void RemoveCallbacks(IFPVActions instance)
        {
            if (m_Wrapper.m_FPVActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFPVActions instance)
        {
            foreach (var item in m_Wrapper.m_FPVActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FPVActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FPVActions @FPV => new FPVActions(this);

    // Top-Down
    private readonly InputActionMap m_TopDown;
    private List<ITopDownActions> m_TopDownActionsCallbackInterfaces = new List<ITopDownActions>();
    private readonly InputAction m_TopDown_ScreenEdgePanning;
    private readonly InputAction m_TopDown_KeyboardCameraMovement;
    private readonly InputAction m_TopDown_ClickAndDrag;
    private readonly InputAction m_TopDown_ZoomCamera;
    private readonly InputAction m_TopDown_Interaction;
    private readonly InputAction m_TopDown_SwitchCamera;
    private readonly InputAction m_TopDown_SwitchCharacter;
    public struct TopDownActions
    {
        private @InputActions m_Wrapper;
        public TopDownActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ScreenEdgePanning => m_Wrapper.m_TopDown_ScreenEdgePanning;
        public InputAction @KeyboardCameraMovement => m_Wrapper.m_TopDown_KeyboardCameraMovement;
        public InputAction @ClickAndDrag => m_Wrapper.m_TopDown_ClickAndDrag;
        public InputAction @ZoomCamera => m_Wrapper.m_TopDown_ZoomCamera;
        public InputAction @Interaction => m_Wrapper.m_TopDown_Interaction;
        public InputAction @SwitchCamera => m_Wrapper.m_TopDown_SwitchCamera;
        public InputAction @SwitchCharacter => m_Wrapper.m_TopDown_SwitchCharacter;
        public InputActionMap Get() { return m_Wrapper.m_TopDown; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TopDownActions set) { return set.Get(); }
        public void AddCallbacks(ITopDownActions instance)
        {
            if (instance == null || m_Wrapper.m_TopDownActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TopDownActionsCallbackInterfaces.Add(instance);
            @ScreenEdgePanning.started += instance.OnScreenEdgePanning;
            @ScreenEdgePanning.performed += instance.OnScreenEdgePanning;
            @ScreenEdgePanning.canceled += instance.OnScreenEdgePanning;
            @KeyboardCameraMovement.started += instance.OnKeyboardCameraMovement;
            @KeyboardCameraMovement.performed += instance.OnKeyboardCameraMovement;
            @KeyboardCameraMovement.canceled += instance.OnKeyboardCameraMovement;
            @ClickAndDrag.started += instance.OnClickAndDrag;
            @ClickAndDrag.performed += instance.OnClickAndDrag;
            @ClickAndDrag.canceled += instance.OnClickAndDrag;
            @ZoomCamera.started += instance.OnZoomCamera;
            @ZoomCamera.performed += instance.OnZoomCamera;
            @ZoomCamera.canceled += instance.OnZoomCamera;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @SwitchCamera.started += instance.OnSwitchCamera;
            @SwitchCamera.performed += instance.OnSwitchCamera;
            @SwitchCamera.canceled += instance.OnSwitchCamera;
            @SwitchCharacter.started += instance.OnSwitchCharacter;
            @SwitchCharacter.performed += instance.OnSwitchCharacter;
            @SwitchCharacter.canceled += instance.OnSwitchCharacter;
        }

        private void UnregisterCallbacks(ITopDownActions instance)
        {
            @ScreenEdgePanning.started -= instance.OnScreenEdgePanning;
            @ScreenEdgePanning.performed -= instance.OnScreenEdgePanning;
            @ScreenEdgePanning.canceled -= instance.OnScreenEdgePanning;
            @KeyboardCameraMovement.started -= instance.OnKeyboardCameraMovement;
            @KeyboardCameraMovement.performed -= instance.OnKeyboardCameraMovement;
            @KeyboardCameraMovement.canceled -= instance.OnKeyboardCameraMovement;
            @ClickAndDrag.started -= instance.OnClickAndDrag;
            @ClickAndDrag.performed -= instance.OnClickAndDrag;
            @ClickAndDrag.canceled -= instance.OnClickAndDrag;
            @ZoomCamera.started -= instance.OnZoomCamera;
            @ZoomCamera.performed -= instance.OnZoomCamera;
            @ZoomCamera.canceled -= instance.OnZoomCamera;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @SwitchCamera.started -= instance.OnSwitchCamera;
            @SwitchCamera.performed -= instance.OnSwitchCamera;
            @SwitchCamera.canceled -= instance.OnSwitchCamera;
            @SwitchCharacter.started -= instance.OnSwitchCharacter;
            @SwitchCharacter.performed -= instance.OnSwitchCharacter;
            @SwitchCharacter.canceled -= instance.OnSwitchCharacter;
        }

        public void RemoveCallbacks(ITopDownActions instance)
        {
            if (m_Wrapper.m_TopDownActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITopDownActions instance)
        {
            foreach (var item in m_Wrapper.m_TopDownActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TopDownActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TopDownActions @TopDown => new TopDownActions(this);

    // Isometric
    private readonly InputActionMap m_Isometric;
    private List<IIsometricActions> m_IsometricActionsCallbackInterfaces = new List<IIsometricActions>();
    private readonly InputAction m_Isometric_Mouse;
    private readonly InputAction m_Isometric_Interaction;
    private readonly InputAction m_Isometric_SwitchCamera;
    private readonly InputAction m_Isometric_SwitchCharacter;
    private readonly InputAction m_Isometric_Movement;
    public struct IsometricActions
    {
        private @InputActions m_Wrapper;
        public IsometricActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Mouse => m_Wrapper.m_Isometric_Mouse;
        public InputAction @Interaction => m_Wrapper.m_Isometric_Interaction;
        public InputAction @SwitchCamera => m_Wrapper.m_Isometric_SwitchCamera;
        public InputAction @SwitchCharacter => m_Wrapper.m_Isometric_SwitchCharacter;
        public InputAction @Movement => m_Wrapper.m_Isometric_Movement;
        public InputActionMap Get() { return m_Wrapper.m_Isometric; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(IsometricActions set) { return set.Get(); }
        public void AddCallbacks(IIsometricActions instance)
        {
            if (instance == null || m_Wrapper.m_IsometricActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_IsometricActionsCallbackInterfaces.Add(instance);
            @Mouse.started += instance.OnMouse;
            @Mouse.performed += instance.OnMouse;
            @Mouse.canceled += instance.OnMouse;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @SwitchCamera.started += instance.OnSwitchCamera;
            @SwitchCamera.performed += instance.OnSwitchCamera;
            @SwitchCamera.canceled += instance.OnSwitchCamera;
            @SwitchCharacter.started += instance.OnSwitchCharacter;
            @SwitchCharacter.performed += instance.OnSwitchCharacter;
            @SwitchCharacter.canceled += instance.OnSwitchCharacter;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
        }

        private void UnregisterCallbacks(IIsometricActions instance)
        {
            @Mouse.started -= instance.OnMouse;
            @Mouse.performed -= instance.OnMouse;
            @Mouse.canceled -= instance.OnMouse;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @SwitchCamera.started -= instance.OnSwitchCamera;
            @SwitchCamera.performed -= instance.OnSwitchCamera;
            @SwitchCamera.canceled -= instance.OnSwitchCamera;
            @SwitchCharacter.started -= instance.OnSwitchCharacter;
            @SwitchCharacter.performed -= instance.OnSwitchCharacter;
            @SwitchCharacter.canceled -= instance.OnSwitchCharacter;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
        }

        public void RemoveCallbacks(IIsometricActions instance)
        {
            if (m_Wrapper.m_IsometricActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IIsometricActions instance)
        {
            foreach (var item in m_Wrapper.m_IsometricActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_IsometricActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public IsometricActions @Isometric => new IsometricActions(this);

    // DefNumbers
    private readonly InputActionMap m_DefNumbers;
    private List<IDefNumbersActions> m_DefNumbersActionsCallbackInterfaces = new List<IDefNumbersActions>();
    private readonly InputAction m_DefNumbers_One;
    private readonly InputAction m_DefNumbers_Two;
    private readonly InputAction m_DefNumbers_Three;
    private readonly InputAction m_DefNumbers_Four;
    private readonly InputAction m_DefNumbers_Five;
    private readonly InputAction m_DefNumbers_Six;
    private readonly InputAction m_DefNumbers_Seven;
    private readonly InputAction m_DefNumbers_Eight;
    private readonly InputAction m_DefNumbers_Nine;
    private readonly InputAction m_DefNumbers_Zero;
    public struct DefNumbersActions
    {
        private @InputActions m_Wrapper;
        public DefNumbersActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @One => m_Wrapper.m_DefNumbers_One;
        public InputAction @Two => m_Wrapper.m_DefNumbers_Two;
        public InputAction @Three => m_Wrapper.m_DefNumbers_Three;
        public InputAction @Four => m_Wrapper.m_DefNumbers_Four;
        public InputAction @Five => m_Wrapper.m_DefNumbers_Five;
        public InputAction @Six => m_Wrapper.m_DefNumbers_Six;
        public InputAction @Seven => m_Wrapper.m_DefNumbers_Seven;
        public InputAction @Eight => m_Wrapper.m_DefNumbers_Eight;
        public InputAction @Nine => m_Wrapper.m_DefNumbers_Nine;
        public InputAction @Zero => m_Wrapper.m_DefNumbers_Zero;
        public InputActionMap Get() { return m_Wrapper.m_DefNumbers; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefNumbersActions set) { return set.Get(); }
        public void AddCallbacks(IDefNumbersActions instance)
        {
            if (instance == null || m_Wrapper.m_DefNumbersActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefNumbersActionsCallbackInterfaces.Add(instance);
            @One.started += instance.OnOne;
            @One.performed += instance.OnOne;
            @One.canceled += instance.OnOne;
            @Two.started += instance.OnTwo;
            @Two.performed += instance.OnTwo;
            @Two.canceled += instance.OnTwo;
            @Three.started += instance.OnThree;
            @Three.performed += instance.OnThree;
            @Three.canceled += instance.OnThree;
            @Four.started += instance.OnFour;
            @Four.performed += instance.OnFour;
            @Four.canceled += instance.OnFour;
            @Five.started += instance.OnFive;
            @Five.performed += instance.OnFive;
            @Five.canceled += instance.OnFive;
            @Six.started += instance.OnSix;
            @Six.performed += instance.OnSix;
            @Six.canceled += instance.OnSix;
            @Seven.started += instance.OnSeven;
            @Seven.performed += instance.OnSeven;
            @Seven.canceled += instance.OnSeven;
            @Eight.started += instance.OnEight;
            @Eight.performed += instance.OnEight;
            @Eight.canceled += instance.OnEight;
            @Nine.started += instance.OnNine;
            @Nine.performed += instance.OnNine;
            @Nine.canceled += instance.OnNine;
            @Zero.started += instance.OnZero;
            @Zero.performed += instance.OnZero;
            @Zero.canceled += instance.OnZero;
        }

        private void UnregisterCallbacks(IDefNumbersActions instance)
        {
            @One.started -= instance.OnOne;
            @One.performed -= instance.OnOne;
            @One.canceled -= instance.OnOne;
            @Two.started -= instance.OnTwo;
            @Two.performed -= instance.OnTwo;
            @Two.canceled -= instance.OnTwo;
            @Three.started -= instance.OnThree;
            @Three.performed -= instance.OnThree;
            @Three.canceled -= instance.OnThree;
            @Four.started -= instance.OnFour;
            @Four.performed -= instance.OnFour;
            @Four.canceled -= instance.OnFour;
            @Five.started -= instance.OnFive;
            @Five.performed -= instance.OnFive;
            @Five.canceled -= instance.OnFive;
            @Six.started -= instance.OnSix;
            @Six.performed -= instance.OnSix;
            @Six.canceled -= instance.OnSix;
            @Seven.started -= instance.OnSeven;
            @Seven.performed -= instance.OnSeven;
            @Seven.canceled -= instance.OnSeven;
            @Eight.started -= instance.OnEight;
            @Eight.performed -= instance.OnEight;
            @Eight.canceled -= instance.OnEight;
            @Nine.started -= instance.OnNine;
            @Nine.performed -= instance.OnNine;
            @Nine.canceled -= instance.OnNine;
            @Zero.started -= instance.OnZero;
            @Zero.performed -= instance.OnZero;
            @Zero.canceled -= instance.OnZero;
        }

        public void RemoveCallbacks(IDefNumbersActions instance)
        {
            if (m_Wrapper.m_DefNumbersActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefNumbersActions instance)
        {
            foreach (var item in m_Wrapper.m_DefNumbersActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefNumbersActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefNumbersActions @DefNumbers => new DefNumbersActions(this);

    // OptionsNumbers
    private readonly InputActionMap m_OptionsNumbers;
    private List<IOptionsNumbersActions> m_OptionsNumbersActionsCallbackInterfaces = new List<IOptionsNumbersActions>();
    private readonly InputAction m_OptionsNumbers_One;
    private readonly InputAction m_OptionsNumbers_Two;
    private readonly InputAction m_OptionsNumbers_Three;
    private readonly InputAction m_OptionsNumbers_Four;
    private readonly InputAction m_OptionsNumbers_Five;
    private readonly InputAction m_OptionsNumbers_Six;
    private readonly InputAction m_OptionsNumbers_Seven;
    private readonly InputAction m_OptionsNumbers_Eight;
    private readonly InputAction m_OptionsNumbers_Nine;
    private readonly InputAction m_OptionsNumbers_Zero;
    public struct OptionsNumbersActions
    {
        private @InputActions m_Wrapper;
        public OptionsNumbersActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @One => m_Wrapper.m_OptionsNumbers_One;
        public InputAction @Two => m_Wrapper.m_OptionsNumbers_Two;
        public InputAction @Three => m_Wrapper.m_OptionsNumbers_Three;
        public InputAction @Four => m_Wrapper.m_OptionsNumbers_Four;
        public InputAction @Five => m_Wrapper.m_OptionsNumbers_Five;
        public InputAction @Six => m_Wrapper.m_OptionsNumbers_Six;
        public InputAction @Seven => m_Wrapper.m_OptionsNumbers_Seven;
        public InputAction @Eight => m_Wrapper.m_OptionsNumbers_Eight;
        public InputAction @Nine => m_Wrapper.m_OptionsNumbers_Nine;
        public InputAction @Zero => m_Wrapper.m_OptionsNumbers_Zero;
        public InputActionMap Get() { return m_Wrapper.m_OptionsNumbers; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OptionsNumbersActions set) { return set.Get(); }
        public void AddCallbacks(IOptionsNumbersActions instance)
        {
            if (instance == null || m_Wrapper.m_OptionsNumbersActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OptionsNumbersActionsCallbackInterfaces.Add(instance);
            @One.started += instance.OnOne;
            @One.performed += instance.OnOne;
            @One.canceled += instance.OnOne;
            @Two.started += instance.OnTwo;
            @Two.performed += instance.OnTwo;
            @Two.canceled += instance.OnTwo;
            @Three.started += instance.OnThree;
            @Three.performed += instance.OnThree;
            @Three.canceled += instance.OnThree;
            @Four.started += instance.OnFour;
            @Four.performed += instance.OnFour;
            @Four.canceled += instance.OnFour;
            @Five.started += instance.OnFive;
            @Five.performed += instance.OnFive;
            @Five.canceled += instance.OnFive;
            @Six.started += instance.OnSix;
            @Six.performed += instance.OnSix;
            @Six.canceled += instance.OnSix;
            @Seven.started += instance.OnSeven;
            @Seven.performed += instance.OnSeven;
            @Seven.canceled += instance.OnSeven;
            @Eight.started += instance.OnEight;
            @Eight.performed += instance.OnEight;
            @Eight.canceled += instance.OnEight;
            @Nine.started += instance.OnNine;
            @Nine.performed += instance.OnNine;
            @Nine.canceled += instance.OnNine;
            @Zero.started += instance.OnZero;
            @Zero.performed += instance.OnZero;
            @Zero.canceled += instance.OnZero;
        }

        private void UnregisterCallbacks(IOptionsNumbersActions instance)
        {
            @One.started -= instance.OnOne;
            @One.performed -= instance.OnOne;
            @One.canceled -= instance.OnOne;
            @Two.started -= instance.OnTwo;
            @Two.performed -= instance.OnTwo;
            @Two.canceled -= instance.OnTwo;
            @Three.started -= instance.OnThree;
            @Three.performed -= instance.OnThree;
            @Three.canceled -= instance.OnThree;
            @Four.started -= instance.OnFour;
            @Four.performed -= instance.OnFour;
            @Four.canceled -= instance.OnFour;
            @Five.started -= instance.OnFive;
            @Five.performed -= instance.OnFive;
            @Five.canceled -= instance.OnFive;
            @Six.started -= instance.OnSix;
            @Six.performed -= instance.OnSix;
            @Six.canceled -= instance.OnSix;
            @Seven.started -= instance.OnSeven;
            @Seven.performed -= instance.OnSeven;
            @Seven.canceled -= instance.OnSeven;
            @Eight.started -= instance.OnEight;
            @Eight.performed -= instance.OnEight;
            @Eight.canceled -= instance.OnEight;
            @Nine.started -= instance.OnNine;
            @Nine.performed -= instance.OnNine;
            @Nine.canceled -= instance.OnNine;
            @Zero.started -= instance.OnZero;
            @Zero.performed -= instance.OnZero;
            @Zero.canceled -= instance.OnZero;
        }

        public void RemoveCallbacks(IOptionsNumbersActions instance)
        {
            if (m_Wrapper.m_OptionsNumbersActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOptionsNumbersActions instance)
        {
            foreach (var item in m_Wrapper.m_OptionsNumbersActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OptionsNumbersActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OptionsNumbersActions @OptionsNumbers => new OptionsNumbersActions(this);
    public interface IFPVActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnSwitchCamera(InputAction.CallbackContext context);
        void OnSwitchCharacter(InputAction.CallbackContext context);
    }
    public interface ITopDownActions
    {
        void OnScreenEdgePanning(InputAction.CallbackContext context);
        void OnKeyboardCameraMovement(InputAction.CallbackContext context);
        void OnClickAndDrag(InputAction.CallbackContext context);
        void OnZoomCamera(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnSwitchCamera(InputAction.CallbackContext context);
        void OnSwitchCharacter(InputAction.CallbackContext context);
    }
    public interface IIsometricActions
    {
        void OnMouse(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnSwitchCamera(InputAction.CallbackContext context);
        void OnSwitchCharacter(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
    }
    public interface IDefNumbersActions
    {
        void OnOne(InputAction.CallbackContext context);
        void OnTwo(InputAction.CallbackContext context);
        void OnThree(InputAction.CallbackContext context);
        void OnFour(InputAction.CallbackContext context);
        void OnFive(InputAction.CallbackContext context);
        void OnSix(InputAction.CallbackContext context);
        void OnSeven(InputAction.CallbackContext context);
        void OnEight(InputAction.CallbackContext context);
        void OnNine(InputAction.CallbackContext context);
        void OnZero(InputAction.CallbackContext context);
    }
    public interface IOptionsNumbersActions
    {
        void OnOne(InputAction.CallbackContext context);
        void OnTwo(InputAction.CallbackContext context);
        void OnThree(InputAction.CallbackContext context);
        void OnFour(InputAction.CallbackContext context);
        void OnFive(InputAction.CallbackContext context);
        void OnSix(InputAction.CallbackContext context);
        void OnSeven(InputAction.CallbackContext context);
        void OnEight(InputAction.CallbackContext context);
        void OnNine(InputAction.CallbackContext context);
        void OnZero(InputAction.CallbackContext context);
    }
}
