//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Data/InputActions/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""FPV"",
            ""id"": ""85262d87-3cda-470a-a018-1482aea3fb96"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""b6fbca7c-5df6-49e1-ab63-6cd9ff80e54e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""b5354137-79ca-4c0c-9f35-a9b5f9902918"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""990d2ea9-44b4-49d5-8414-9c3e5f1be62b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCamera"",
                    ""type"": ""Button"",
                    ""id"": ""99e78472-ef1f-4a7f-91ad-91c1fe4e6260"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""One"",
                    ""type"": ""Button"",
                    ""id"": ""b3dc8348-3937-4b17-9aac-2738b7a7cc96"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two"",
                    ""type"": ""Button"",
                    ""id"": ""cf97ae4f-24de-48f4-8dc1-0c93fc062ab0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three"",
                    ""type"": ""Button"",
                    ""id"": ""ad1bca31-67c1-404c-9feb-5ac04fed8b04"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Four"",
                    ""type"": ""Button"",
                    ""id"": ""a76222e0-ca1f-4d1e-a00f-e448de7fee47"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Five"",
                    ""type"": ""Button"",
                    ""id"": ""254e891a-e4a7-48d9-81a1-c69388311718"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Six"",
                    ""type"": ""Button"",
                    ""id"": ""bb924887-7649-404f-87de-c135fab9d211"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Seven"",
                    ""type"": ""Button"",
                    ""id"": ""b4ed1be9-acaa-48dc-addd-1fea6167e297"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eight"",
                    ""type"": ""Button"",
                    ""id"": ""b7d524fc-7882-4385-b653-a15bb3fd3fce"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Nine"",
                    ""type"": ""Button"",
                    ""id"": ""bcd7d379-27f1-421f-ada6-7035262ffad8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zero"",
                    ""type"": ""Button"",
                    ""id"": ""8a0d8290-4a21-4461-874b-65a797c92a7e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""3bf926aa-a224-472f-9ad8-b7f04588d1cd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9cd723c6-abc0-4f07-970e-a1fc7698e9f9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1119038f-f069-4956-847f-786a56d8d9ee"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3a50e9ef-3bf0-44b8-af81-e1ec1dbf932b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f467084d-c68d-44ac-a7a6-d7b14854c0ef"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3663f57f-acdd-431d-a441-961e69f5c3dc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d7b7df75-8de8-46ce-9211-7dfa65845798"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67414e4d-eb6b-40df-b12e-da827f0e32f8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13d36c30-9382-4f8c-a464-e825045f935d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0d0688c-4fc5-4242-b986-bf04299d6e3a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""One"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2d747bb-0dae-4016-90e1-87cb031173f1"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Two"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ae650df-2fbe-4ca9-982e-078cd023b54a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Three"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a4be545-69d1-400e-b315-e9a46f09ae56"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Four"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b5b0801-36da-48b3-a435-a43e690a168c"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Five"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96d33f9d-a1fa-4059-9650-e0c20094901a"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Six"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84eeb322-36e7-4bfa-9be3-b30bb2ba94ae"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Seven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fbc2f26-78c1-4b64-9cb2-d11eb588fe12"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Eight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34da5e20-3e6e-49f2-a2a3-aaa3496ba2d4"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6e62c9f-78f0-457a-8fd4-e7c495248553"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64453b48-f13c-41bd-aeff-508ab13a9dde"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Top-Down"",
            ""id"": ""769e8037-b798-435a-9e1d-afde285c0a7b"",
            ""actions"": [
                {
                    ""name"": ""KeyboardCameraMovement"",
                    ""type"": ""Value"",
                    ""id"": ""cfab4d47-57f7-446d-ab31-df879ef9dd41"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScreenEdgePanning"",
                    ""type"": ""Value"",
                    ""id"": ""42149a0f-314e-4e42-b309-60a2008d51dd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClickAndDrag"",
                    ""type"": ""Button"",
                    ""id"": ""29f399b9-f17d-4c25-ab35-ceb884774b63"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomCamera"",
                    ""type"": ""Value"",
                    ""id"": ""6c077486-98db-4dbf-b085-228ec429aa8e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""b6a00bf1-82a5-4add-a045-cc250d387aae"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCamera"",
                    ""type"": ""Button"",
                    ""id"": ""f0a3cafc-2418-4885-a70a-af4882de117c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""One"",
                    ""type"": ""Button"",
                    ""id"": ""68b5a8ca-ea43-4746-ab50-09f7d6bf10f0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two"",
                    ""type"": ""Button"",
                    ""id"": ""96378a75-3e40-48d9-9d6a-bc8912df8bd0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three"",
                    ""type"": ""Button"",
                    ""id"": ""a128e29b-356c-4855-8738-7d4b44db58ce"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Four"",
                    ""type"": ""Button"",
                    ""id"": ""8a457974-4a0d-43a3-b368-e5ee50c16912"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Five"",
                    ""type"": ""Button"",
                    ""id"": ""34b12977-7bf5-4318-9149-4bfc4fa02c7d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Six"",
                    ""type"": ""Button"",
                    ""id"": ""ea167d79-74cd-4c1d-ac88-077570b28b48"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Seven"",
                    ""type"": ""Button"",
                    ""id"": ""311b7f96-89e7-4462-b018-f5ddd5f76b8b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eight"",
                    ""type"": ""Button"",
                    ""id"": ""fc89bff9-da44-4d32-b7fc-1ab5a1327190"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Nine"",
                    ""type"": ""Button"",
                    ""id"": ""25777571-8459-4e23-b8b9-a5fecb1833ba"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zero"",
                    ""type"": ""Button"",
                    ""id"": ""81258afc-c776-4f35-8954-79b4880a6aa4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""a22b4709-551e-4840-a306-1bc6131f63c5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5d1080f0-1a61-4176-9bf6-e4603d3bd9ad"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardCameraMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eabb9363-b8f9-4f6e-a7c1-1015d299bde3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardCameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e762a709-cd3a-48fa-bf9f-26b11ce7567d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardCameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d0f6aa15-98ca-4219-9328-23af5b9f1424"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardCameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f8d55e7e-dc00-4aa0-9952-3a40d1ef278b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardCameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8d32385d-5fb7-4856-b4ff-d2878158552b"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7683a027-e2cc-4cf6-8107-7831a86668b9"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e464a20-1021-42db-980e-e7def9f47117"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4335457-9dbd-486f-8369-5ddd33e8463d"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Eight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8652b0a-201b-435d-b584-ea7a215b2dbc"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Seven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89de40e7-669a-4857-ba93-ef258b85c8aa"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Six"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fbab61f-87fb-4168-89dc-18a56b2610c9"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Five"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c672bbf3-3055-4a11-afd7-f7e5c4758f4a"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Four"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d98c9a3-5796-477f-b528-e1ece206abce"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Three"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f591bac-6d22-4a2d-a098-ad04e8222027"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Two"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f35f9d72-53d3-4e90-b61f-ece5566deee6"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""One"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""968bc627-58cd-42e6-8dfa-cf203c7aff30"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afc6d4e9-8d80-4dc1-89c4-26a59fbdc5fb"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c83bd80c-886b-4eb2-b8cb-57ac1cfc25bb"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScreenEdgePanning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c840c0d2-eee8-40be-a61d-af1717ec742c"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickAndDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab5f341e-8257-42f1-ad4f-7e02047a2172"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Isometric"",
            ""id"": ""9e2e56e4-eb88-45b1-b3bd-1a160902f751"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""41c269c8-bb0c-4bff-bee5-923bdda2ce24"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Value"",
                    ""id"": ""b6ea6928-f18f-4bc1-a6ce-c0fcdcf13ec9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""2e6b0af4-1b11-4cc4-8495-30271496bb72"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCamera"",
                    ""type"": ""Button"",
                    ""id"": ""a96743d7-b5bf-4e14-9a99-88c73b0f9ba6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""One"",
                    ""type"": ""Button"",
                    ""id"": ""a73f9af4-a08e-476d-81cf-3f7b3364fd7c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two"",
                    ""type"": ""Button"",
                    ""id"": ""7a4d8df3-4cbd-47a4-9816-5392b8c98f4f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three"",
                    ""type"": ""Button"",
                    ""id"": ""2c1345cf-006e-46bc-b5b2-497093e4a103"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Four"",
                    ""type"": ""Button"",
                    ""id"": ""68ae312d-79e9-4846-a9d3-4d8d40ef63a2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Five"",
                    ""type"": ""Button"",
                    ""id"": ""94800c63-638d-42de-9b43-a452510efb53"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Six"",
                    ""type"": ""Button"",
                    ""id"": ""07323e47-c52f-48eb-9508-0a1fb716dceb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Seven"",
                    ""type"": ""Button"",
                    ""id"": ""c736ad1e-c8b4-48be-8904-098a5027653f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eight"",
                    ""type"": ""Button"",
                    ""id"": ""7e82fc38-680f-4896-b746-ec88a04ecd96"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Nine"",
                    ""type"": ""Button"",
                    ""id"": ""2bc85fc6-c80d-4658-adaf-5447a2d6a19a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zero"",
                    ""type"": ""Button"",
                    ""id"": ""c2819861-fa74-49e4-bd6d-9cf795eaef1f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""84e5d877-75cf-49ea-9142-ef905c4a8238"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""79a27341-391f-4cb3-9539-492631ca0c28"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7ac9156e-d2fd-40ea-a517-e2d56559cf27"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b32d4dfc-791c-458f-aa08-e65a86f97146"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""45fcad4a-e572-4add-9cd3-1503d44e2067"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""886078ba-cb4c-4921-889d-7b03fbf4d197"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""81f11c4c-03a9-4c18-83cf-639fba9e5136"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6d22f61-d7bc-43f9-9170-653dfa4bc853"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77d76706-fb8c-4724-a2a6-e6e91907d353"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""809c9160-76f1-4e89-9c8d-7fed0b00ba8d"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Eight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97b89650-30af-4706-9688-f25f6cecec4f"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Seven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed475423-705a-4857-b9bd-87dd6616f5bd"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Six"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d9e7597-a8f1-4ad3-a9f9-b2bab3e29f44"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Five"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c805be1-c221-43c3-a0f3-11d7fccb7218"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Four"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""122d0902-59d4-470c-abaf-d1071d257503"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Three"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4ecb731-4cf5-4d90-a46c-16e6f926d607"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Two"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3031805b-bf60-4aca-a165-58b8a74fbe53"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""One"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12da11d6-6c20-4246-9b4e-4b3a1b328fc4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35be2daf-3671-477e-88c1-7d63acc7e65a"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9036dd3-ae9f-4c19-99de-ca39583d7a80"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // FPV
        m_FPV = asset.FindActionMap("FPV", throwIfNotFound: true);
        m_FPV_Movement = m_FPV.FindAction("Movement", throwIfNotFound: true);
        m_FPV_RotateCamera = m_FPV.FindAction("RotateCamera", throwIfNotFound: true);
        m_FPV_Interaction = m_FPV.FindAction("Interaction", throwIfNotFound: true);
        m_FPV_SwitchCamera = m_FPV.FindAction("SwitchCamera", throwIfNotFound: true);
        m_FPV_One = m_FPV.FindAction("One", throwIfNotFound: true);
        m_FPV_Two = m_FPV.FindAction("Two", throwIfNotFound: true);
        m_FPV_Three = m_FPV.FindAction("Three", throwIfNotFound: true);
        m_FPV_Four = m_FPV.FindAction("Four", throwIfNotFound: true);
        m_FPV_Five = m_FPV.FindAction("Five", throwIfNotFound: true);
        m_FPV_Six = m_FPV.FindAction("Six", throwIfNotFound: true);
        m_FPV_Seven = m_FPV.FindAction("Seven", throwIfNotFound: true);
        m_FPV_Eight = m_FPV.FindAction("Eight", throwIfNotFound: true);
        m_FPV_Nine = m_FPV.FindAction("Nine", throwIfNotFound: true);
        m_FPV_Zero = m_FPV.FindAction("Zero", throwIfNotFound: true);
        m_FPV_SwitchCharacter = m_FPV.FindAction("SwitchCharacter", throwIfNotFound: true);
        // Top-Down
        m_TopDown = asset.FindActionMap("Top-Down", throwIfNotFound: true);
        m_TopDown_KeyboardCameraMovement = m_TopDown.FindAction("KeyboardCameraMovement", throwIfNotFound: true);
        m_TopDown_ScreenEdgePanning = m_TopDown.FindAction("ScreenEdgePanning", throwIfNotFound: true);
        m_TopDown_ClickAndDrag = m_TopDown.FindAction("ClickAndDrag", throwIfNotFound: true);
        m_TopDown_ZoomCamera = m_TopDown.FindAction("ZoomCamera", throwIfNotFound: true);
        m_TopDown_Interaction = m_TopDown.FindAction("Interaction", throwIfNotFound: true);
        m_TopDown_SwitchCamera = m_TopDown.FindAction("SwitchCamera", throwIfNotFound: true);
        m_TopDown_One = m_TopDown.FindAction("One", throwIfNotFound: true);
        m_TopDown_Two = m_TopDown.FindAction("Two", throwIfNotFound: true);
        m_TopDown_Three = m_TopDown.FindAction("Three", throwIfNotFound: true);
        m_TopDown_Four = m_TopDown.FindAction("Four", throwIfNotFound: true);
        m_TopDown_Five = m_TopDown.FindAction("Five", throwIfNotFound: true);
        m_TopDown_Six = m_TopDown.FindAction("Six", throwIfNotFound: true);
        m_TopDown_Seven = m_TopDown.FindAction("Seven", throwIfNotFound: true);
        m_TopDown_Eight = m_TopDown.FindAction("Eight", throwIfNotFound: true);
        m_TopDown_Nine = m_TopDown.FindAction("Nine", throwIfNotFound: true);
        m_TopDown_Zero = m_TopDown.FindAction("Zero", throwIfNotFound: true);
        m_TopDown_SwitchCharacter = m_TopDown.FindAction("SwitchCharacter", throwIfNotFound: true);
        // Isometric
        m_Isometric = asset.FindActionMap("Isometric", throwIfNotFound: true);
        m_Isometric_Movement = m_Isometric.FindAction("Movement", throwIfNotFound: true);
        m_Isometric_Mouse = m_Isometric.FindAction("Mouse", throwIfNotFound: true);
        m_Isometric_Interaction = m_Isometric.FindAction("Interaction", throwIfNotFound: true);
        m_Isometric_SwitchCamera = m_Isometric.FindAction("SwitchCamera", throwIfNotFound: true);
        m_Isometric_One = m_Isometric.FindAction("One", throwIfNotFound: true);
        m_Isometric_Two = m_Isometric.FindAction("Two", throwIfNotFound: true);
        m_Isometric_Three = m_Isometric.FindAction("Three", throwIfNotFound: true);
        m_Isometric_Four = m_Isometric.FindAction("Four", throwIfNotFound: true);
        m_Isometric_Five = m_Isometric.FindAction("Five", throwIfNotFound: true);
        m_Isometric_Six = m_Isometric.FindAction("Six", throwIfNotFound: true);
        m_Isometric_Seven = m_Isometric.FindAction("Seven", throwIfNotFound: true);
        m_Isometric_Eight = m_Isometric.FindAction("Eight", throwIfNotFound: true);
        m_Isometric_Nine = m_Isometric.FindAction("Nine", throwIfNotFound: true);
        m_Isometric_Zero = m_Isometric.FindAction("Zero", throwIfNotFound: true);
        m_Isometric_SwitchCharacter = m_Isometric.FindAction("SwitchCharacter", throwIfNotFound: true);
    }

    ~@InputActions()
    {
        UnityEngine.Debug.Assert(!m_FPV.enabled, "This will cause a leak and performance issues, InputActions.FPV.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_TopDown.enabled, "This will cause a leak and performance issues, InputActions.TopDown.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Isometric.enabled, "This will cause a leak and performance issues, InputActions.Isometric.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FPV
    private readonly InputActionMap m_FPV;
    private List<IFPVActions> m_FPVActionsCallbackInterfaces = new List<IFPVActions>();
    private readonly InputAction m_FPV_Movement;
    private readonly InputAction m_FPV_RotateCamera;
    private readonly InputAction m_FPV_Interaction;
    private readonly InputAction m_FPV_SwitchCamera;
    private readonly InputAction m_FPV_One;
    private readonly InputAction m_FPV_Two;
    private readonly InputAction m_FPV_Three;
    private readonly InputAction m_FPV_Four;
    private readonly InputAction m_FPV_Five;
    private readonly InputAction m_FPV_Six;
    private readonly InputAction m_FPV_Seven;
    private readonly InputAction m_FPV_Eight;
    private readonly InputAction m_FPV_Nine;
    private readonly InputAction m_FPV_Zero;
    private readonly InputAction m_FPV_SwitchCharacter;
    public struct FPVActions
    {
        private @InputActions m_Wrapper;
        public FPVActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_FPV_Movement;
        public InputAction @RotateCamera => m_Wrapper.m_FPV_RotateCamera;
        public InputAction @Interaction => m_Wrapper.m_FPV_Interaction;
        public InputAction @SwitchCamera => m_Wrapper.m_FPV_SwitchCamera;
        public InputAction @One => m_Wrapper.m_FPV_One;
        public InputAction @Two => m_Wrapper.m_FPV_Two;
        public InputAction @Three => m_Wrapper.m_FPV_Three;
        public InputAction @Four => m_Wrapper.m_FPV_Four;
        public InputAction @Five => m_Wrapper.m_FPV_Five;
        public InputAction @Six => m_Wrapper.m_FPV_Six;
        public InputAction @Seven => m_Wrapper.m_FPV_Seven;
        public InputAction @Eight => m_Wrapper.m_FPV_Eight;
        public InputAction @Nine => m_Wrapper.m_FPV_Nine;
        public InputAction @Zero => m_Wrapper.m_FPV_Zero;
        public InputAction @SwitchCharacter => m_Wrapper.m_FPV_SwitchCharacter;
        public InputActionMap Get() { return m_Wrapper.m_FPV; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FPVActions set) { return set.Get(); }
        public void AddCallbacks(IFPVActions instance)
        {
            if (instance == null || m_Wrapper.m_FPVActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FPVActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @RotateCamera.started += instance.OnRotateCamera;
            @RotateCamera.performed += instance.OnRotateCamera;
            @RotateCamera.canceled += instance.OnRotateCamera;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @SwitchCamera.started += instance.OnSwitchCamera;
            @SwitchCamera.performed += instance.OnSwitchCamera;
            @SwitchCamera.canceled += instance.OnSwitchCamera;
            @One.started += instance.OnOne;
            @One.performed += instance.OnOne;
            @One.canceled += instance.OnOne;
            @Two.started += instance.OnTwo;
            @Two.performed += instance.OnTwo;
            @Two.canceled += instance.OnTwo;
            @Three.started += instance.OnThree;
            @Three.performed += instance.OnThree;
            @Three.canceled += instance.OnThree;
            @Four.started += instance.OnFour;
            @Four.performed += instance.OnFour;
            @Four.canceled += instance.OnFour;
            @Five.started += instance.OnFive;
            @Five.performed += instance.OnFive;
            @Five.canceled += instance.OnFive;
            @Six.started += instance.OnSix;
            @Six.performed += instance.OnSix;
            @Six.canceled += instance.OnSix;
            @Seven.started += instance.OnSeven;
            @Seven.performed += instance.OnSeven;
            @Seven.canceled += instance.OnSeven;
            @Eight.started += instance.OnEight;
            @Eight.performed += instance.OnEight;
            @Eight.canceled += instance.OnEight;
            @Nine.started += instance.OnNine;
            @Nine.performed += instance.OnNine;
            @Nine.canceled += instance.OnNine;
            @Zero.started += instance.OnZero;
            @Zero.performed += instance.OnZero;
            @Zero.canceled += instance.OnZero;
            @SwitchCharacter.started += instance.OnSwitchCharacter;
            @SwitchCharacter.performed += instance.OnSwitchCharacter;
            @SwitchCharacter.canceled += instance.OnSwitchCharacter;
        }

        private void UnregisterCallbacks(IFPVActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @RotateCamera.started -= instance.OnRotateCamera;
            @RotateCamera.performed -= instance.OnRotateCamera;
            @RotateCamera.canceled -= instance.OnRotateCamera;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @SwitchCamera.started -= instance.OnSwitchCamera;
            @SwitchCamera.performed -= instance.OnSwitchCamera;
            @SwitchCamera.canceled -= instance.OnSwitchCamera;
            @One.started -= instance.OnOne;
            @One.performed -= instance.OnOne;
            @One.canceled -= instance.OnOne;
            @Two.started -= instance.OnTwo;
            @Two.performed -= instance.OnTwo;
            @Two.canceled -= instance.OnTwo;
            @Three.started -= instance.OnThree;
            @Three.performed -= instance.OnThree;
            @Three.canceled -= instance.OnThree;
            @Four.started -= instance.OnFour;
            @Four.performed -= instance.OnFour;
            @Four.canceled -= instance.OnFour;
            @Five.started -= instance.OnFive;
            @Five.performed -= instance.OnFive;
            @Five.canceled -= instance.OnFive;
            @Six.started -= instance.OnSix;
            @Six.performed -= instance.OnSix;
            @Six.canceled -= instance.OnSix;
            @Seven.started -= instance.OnSeven;
            @Seven.performed -= instance.OnSeven;
            @Seven.canceled -= instance.OnSeven;
            @Eight.started -= instance.OnEight;
            @Eight.performed -= instance.OnEight;
            @Eight.canceled -= instance.OnEight;
            @Nine.started -= instance.OnNine;
            @Nine.performed -= instance.OnNine;
            @Nine.canceled -= instance.OnNine;
            @Zero.started -= instance.OnZero;
            @Zero.performed -= instance.OnZero;
            @Zero.canceled -= instance.OnZero;
            @SwitchCharacter.started -= instance.OnSwitchCharacter;
            @SwitchCharacter.performed -= instance.OnSwitchCharacter;
            @SwitchCharacter.canceled -= instance.OnSwitchCharacter;
        }

        public void RemoveCallbacks(IFPVActions instance)
        {
            if (m_Wrapper.m_FPVActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFPVActions instance)
        {
            foreach (var item in m_Wrapper.m_FPVActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FPVActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FPVActions @FPV => new FPVActions(this);

    // Top-Down
    private readonly InputActionMap m_TopDown;
    private List<ITopDownActions> m_TopDownActionsCallbackInterfaces = new List<ITopDownActions>();
    private readonly InputAction m_TopDown_KeyboardCameraMovement;
    private readonly InputAction m_TopDown_ScreenEdgePanning;
    private readonly InputAction m_TopDown_ClickAndDrag;
    private readonly InputAction m_TopDown_ZoomCamera;
    private readonly InputAction m_TopDown_Interaction;
    private readonly InputAction m_TopDown_SwitchCamera;
    private readonly InputAction m_TopDown_One;
    private readonly InputAction m_TopDown_Two;
    private readonly InputAction m_TopDown_Three;
    private readonly InputAction m_TopDown_Four;
    private readonly InputAction m_TopDown_Five;
    private readonly InputAction m_TopDown_Six;
    private readonly InputAction m_TopDown_Seven;
    private readonly InputAction m_TopDown_Eight;
    private readonly InputAction m_TopDown_Nine;
    private readonly InputAction m_TopDown_Zero;
    private readonly InputAction m_TopDown_SwitchCharacter;
    public struct TopDownActions
    {
        private @InputActions m_Wrapper;
        public TopDownActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @KeyboardCameraMovement => m_Wrapper.m_TopDown_KeyboardCameraMovement;
        public InputAction @ScreenEdgePanning => m_Wrapper.m_TopDown_ScreenEdgePanning;
        public InputAction @ClickAndDrag => m_Wrapper.m_TopDown_ClickAndDrag;
        public InputAction @ZoomCamera => m_Wrapper.m_TopDown_ZoomCamera;
        public InputAction @Interaction => m_Wrapper.m_TopDown_Interaction;
        public InputAction @SwitchCamera => m_Wrapper.m_TopDown_SwitchCamera;
        public InputAction @One => m_Wrapper.m_TopDown_One;
        public InputAction @Two => m_Wrapper.m_TopDown_Two;
        public InputAction @Three => m_Wrapper.m_TopDown_Three;
        public InputAction @Four => m_Wrapper.m_TopDown_Four;
        public InputAction @Five => m_Wrapper.m_TopDown_Five;
        public InputAction @Six => m_Wrapper.m_TopDown_Six;
        public InputAction @Seven => m_Wrapper.m_TopDown_Seven;
        public InputAction @Eight => m_Wrapper.m_TopDown_Eight;
        public InputAction @Nine => m_Wrapper.m_TopDown_Nine;
        public InputAction @Zero => m_Wrapper.m_TopDown_Zero;
        public InputAction @SwitchCharacter => m_Wrapper.m_TopDown_SwitchCharacter;
        public InputActionMap Get() { return m_Wrapper.m_TopDown; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TopDownActions set) { return set.Get(); }
        public void AddCallbacks(ITopDownActions instance)
        {
            if (instance == null || m_Wrapper.m_TopDownActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TopDownActionsCallbackInterfaces.Add(instance);
            @KeyboardCameraMovement.started += instance.OnKeyboardCameraMovement;
            @KeyboardCameraMovement.performed += instance.OnKeyboardCameraMovement;
            @KeyboardCameraMovement.canceled += instance.OnKeyboardCameraMovement;
            @ScreenEdgePanning.started += instance.OnScreenEdgePanning;
            @ScreenEdgePanning.performed += instance.OnScreenEdgePanning;
            @ScreenEdgePanning.canceled += instance.OnScreenEdgePanning;
            @ClickAndDrag.started += instance.OnClickAndDrag;
            @ClickAndDrag.performed += instance.OnClickAndDrag;
            @ClickAndDrag.canceled += instance.OnClickAndDrag;
            @ZoomCamera.started += instance.OnZoomCamera;
            @ZoomCamera.performed += instance.OnZoomCamera;
            @ZoomCamera.canceled += instance.OnZoomCamera;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @SwitchCamera.started += instance.OnSwitchCamera;
            @SwitchCamera.performed += instance.OnSwitchCamera;
            @SwitchCamera.canceled += instance.OnSwitchCamera;
            @One.started += instance.OnOne;
            @One.performed += instance.OnOne;
            @One.canceled += instance.OnOne;
            @Two.started += instance.OnTwo;
            @Two.performed += instance.OnTwo;
            @Two.canceled += instance.OnTwo;
            @Three.started += instance.OnThree;
            @Three.performed += instance.OnThree;
            @Three.canceled += instance.OnThree;
            @Four.started += instance.OnFour;
            @Four.performed += instance.OnFour;
            @Four.canceled += instance.OnFour;
            @Five.started += instance.OnFive;
            @Five.performed += instance.OnFive;
            @Five.canceled += instance.OnFive;
            @Six.started += instance.OnSix;
            @Six.performed += instance.OnSix;
            @Six.canceled += instance.OnSix;
            @Seven.started += instance.OnSeven;
            @Seven.performed += instance.OnSeven;
            @Seven.canceled += instance.OnSeven;
            @Eight.started += instance.OnEight;
            @Eight.performed += instance.OnEight;
            @Eight.canceled += instance.OnEight;
            @Nine.started += instance.OnNine;
            @Nine.performed += instance.OnNine;
            @Nine.canceled += instance.OnNine;
            @Zero.started += instance.OnZero;
            @Zero.performed += instance.OnZero;
            @Zero.canceled += instance.OnZero;
            @SwitchCharacter.started += instance.OnSwitchCharacter;
            @SwitchCharacter.performed += instance.OnSwitchCharacter;
            @SwitchCharacter.canceled += instance.OnSwitchCharacter;
        }

        private void UnregisterCallbacks(ITopDownActions instance)
        {
            @KeyboardCameraMovement.started -= instance.OnKeyboardCameraMovement;
            @KeyboardCameraMovement.performed -= instance.OnKeyboardCameraMovement;
            @KeyboardCameraMovement.canceled -= instance.OnKeyboardCameraMovement;
            @ScreenEdgePanning.started -= instance.OnScreenEdgePanning;
            @ScreenEdgePanning.performed -= instance.OnScreenEdgePanning;
            @ScreenEdgePanning.canceled -= instance.OnScreenEdgePanning;
            @ClickAndDrag.started -= instance.OnClickAndDrag;
            @ClickAndDrag.performed -= instance.OnClickAndDrag;
            @ClickAndDrag.canceled -= instance.OnClickAndDrag;
            @ZoomCamera.started -= instance.OnZoomCamera;
            @ZoomCamera.performed -= instance.OnZoomCamera;
            @ZoomCamera.canceled -= instance.OnZoomCamera;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @SwitchCamera.started -= instance.OnSwitchCamera;
            @SwitchCamera.performed -= instance.OnSwitchCamera;
            @SwitchCamera.canceled -= instance.OnSwitchCamera;
            @One.started -= instance.OnOne;
            @One.performed -= instance.OnOne;
            @One.canceled -= instance.OnOne;
            @Two.started -= instance.OnTwo;
            @Two.performed -= instance.OnTwo;
            @Two.canceled -= instance.OnTwo;
            @Three.started -= instance.OnThree;
            @Three.performed -= instance.OnThree;
            @Three.canceled -= instance.OnThree;
            @Four.started -= instance.OnFour;
            @Four.performed -= instance.OnFour;
            @Four.canceled -= instance.OnFour;
            @Five.started -= instance.OnFive;
            @Five.performed -= instance.OnFive;
            @Five.canceled -= instance.OnFive;
            @Six.started -= instance.OnSix;
            @Six.performed -= instance.OnSix;
            @Six.canceled -= instance.OnSix;
            @Seven.started -= instance.OnSeven;
            @Seven.performed -= instance.OnSeven;
            @Seven.canceled -= instance.OnSeven;
            @Eight.started -= instance.OnEight;
            @Eight.performed -= instance.OnEight;
            @Eight.canceled -= instance.OnEight;
            @Nine.started -= instance.OnNine;
            @Nine.performed -= instance.OnNine;
            @Nine.canceled -= instance.OnNine;
            @Zero.started -= instance.OnZero;
            @Zero.performed -= instance.OnZero;
            @Zero.canceled -= instance.OnZero;
            @SwitchCharacter.started -= instance.OnSwitchCharacter;
            @SwitchCharacter.performed -= instance.OnSwitchCharacter;
            @SwitchCharacter.canceled -= instance.OnSwitchCharacter;
        }

        public void RemoveCallbacks(ITopDownActions instance)
        {
            if (m_Wrapper.m_TopDownActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITopDownActions instance)
        {
            foreach (var item in m_Wrapper.m_TopDownActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TopDownActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TopDownActions @TopDown => new TopDownActions(this);

    // Isometric
    private readonly InputActionMap m_Isometric;
    private List<IIsometricActions> m_IsometricActionsCallbackInterfaces = new List<IIsometricActions>();
    private readonly InputAction m_Isometric_Movement;
    private readonly InputAction m_Isometric_Mouse;
    private readonly InputAction m_Isometric_Interaction;
    private readonly InputAction m_Isometric_SwitchCamera;
    private readonly InputAction m_Isometric_One;
    private readonly InputAction m_Isometric_Two;
    private readonly InputAction m_Isometric_Three;
    private readonly InputAction m_Isometric_Four;
    private readonly InputAction m_Isometric_Five;
    private readonly InputAction m_Isometric_Six;
    private readonly InputAction m_Isometric_Seven;
    private readonly InputAction m_Isometric_Eight;
    private readonly InputAction m_Isometric_Nine;
    private readonly InputAction m_Isometric_Zero;
    private readonly InputAction m_Isometric_SwitchCharacter;
    public struct IsometricActions
    {
        private @InputActions m_Wrapper;
        public IsometricActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Isometric_Movement;
        public InputAction @Mouse => m_Wrapper.m_Isometric_Mouse;
        public InputAction @Interaction => m_Wrapper.m_Isometric_Interaction;
        public InputAction @SwitchCamera => m_Wrapper.m_Isometric_SwitchCamera;
        public InputAction @One => m_Wrapper.m_Isometric_One;
        public InputAction @Two => m_Wrapper.m_Isometric_Two;
        public InputAction @Three => m_Wrapper.m_Isometric_Three;
        public InputAction @Four => m_Wrapper.m_Isometric_Four;
        public InputAction @Five => m_Wrapper.m_Isometric_Five;
        public InputAction @Six => m_Wrapper.m_Isometric_Six;
        public InputAction @Seven => m_Wrapper.m_Isometric_Seven;
        public InputAction @Eight => m_Wrapper.m_Isometric_Eight;
        public InputAction @Nine => m_Wrapper.m_Isometric_Nine;
        public InputAction @Zero => m_Wrapper.m_Isometric_Zero;
        public InputAction @SwitchCharacter => m_Wrapper.m_Isometric_SwitchCharacter;
        public InputActionMap Get() { return m_Wrapper.m_Isometric; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(IsometricActions set) { return set.Get(); }
        public void AddCallbacks(IIsometricActions instance)
        {
            if (instance == null || m_Wrapper.m_IsometricActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_IsometricActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Mouse.started += instance.OnMouse;
            @Mouse.performed += instance.OnMouse;
            @Mouse.canceled += instance.OnMouse;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @SwitchCamera.started += instance.OnSwitchCamera;
            @SwitchCamera.performed += instance.OnSwitchCamera;
            @SwitchCamera.canceled += instance.OnSwitchCamera;
            @One.started += instance.OnOne;
            @One.performed += instance.OnOne;
            @One.canceled += instance.OnOne;
            @Two.started += instance.OnTwo;
            @Two.performed += instance.OnTwo;
            @Two.canceled += instance.OnTwo;
            @Three.started += instance.OnThree;
            @Three.performed += instance.OnThree;
            @Three.canceled += instance.OnThree;
            @Four.started += instance.OnFour;
            @Four.performed += instance.OnFour;
            @Four.canceled += instance.OnFour;
            @Five.started += instance.OnFive;
            @Five.performed += instance.OnFive;
            @Five.canceled += instance.OnFive;
            @Six.started += instance.OnSix;
            @Six.performed += instance.OnSix;
            @Six.canceled += instance.OnSix;
            @Seven.started += instance.OnSeven;
            @Seven.performed += instance.OnSeven;
            @Seven.canceled += instance.OnSeven;
            @Eight.started += instance.OnEight;
            @Eight.performed += instance.OnEight;
            @Eight.canceled += instance.OnEight;
            @Nine.started += instance.OnNine;
            @Nine.performed += instance.OnNine;
            @Nine.canceled += instance.OnNine;
            @Zero.started += instance.OnZero;
            @Zero.performed += instance.OnZero;
            @Zero.canceled += instance.OnZero;
            @SwitchCharacter.started += instance.OnSwitchCharacter;
            @SwitchCharacter.performed += instance.OnSwitchCharacter;
            @SwitchCharacter.canceled += instance.OnSwitchCharacter;
        }

        private void UnregisterCallbacks(IIsometricActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Mouse.started -= instance.OnMouse;
            @Mouse.performed -= instance.OnMouse;
            @Mouse.canceled -= instance.OnMouse;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @SwitchCamera.started -= instance.OnSwitchCamera;
            @SwitchCamera.performed -= instance.OnSwitchCamera;
            @SwitchCamera.canceled -= instance.OnSwitchCamera;
            @One.started -= instance.OnOne;
            @One.performed -= instance.OnOne;
            @One.canceled -= instance.OnOne;
            @Two.started -= instance.OnTwo;
            @Two.performed -= instance.OnTwo;
            @Two.canceled -= instance.OnTwo;
            @Three.started -= instance.OnThree;
            @Three.performed -= instance.OnThree;
            @Three.canceled -= instance.OnThree;
            @Four.started -= instance.OnFour;
            @Four.performed -= instance.OnFour;
            @Four.canceled -= instance.OnFour;
            @Five.started -= instance.OnFive;
            @Five.performed -= instance.OnFive;
            @Five.canceled -= instance.OnFive;
            @Six.started -= instance.OnSix;
            @Six.performed -= instance.OnSix;
            @Six.canceled -= instance.OnSix;
            @Seven.started -= instance.OnSeven;
            @Seven.performed -= instance.OnSeven;
            @Seven.canceled -= instance.OnSeven;
            @Eight.started -= instance.OnEight;
            @Eight.performed -= instance.OnEight;
            @Eight.canceled -= instance.OnEight;
            @Nine.started -= instance.OnNine;
            @Nine.performed -= instance.OnNine;
            @Nine.canceled -= instance.OnNine;
            @Zero.started -= instance.OnZero;
            @Zero.performed -= instance.OnZero;
            @Zero.canceled -= instance.OnZero;
            @SwitchCharacter.started -= instance.OnSwitchCharacter;
            @SwitchCharacter.performed -= instance.OnSwitchCharacter;
            @SwitchCharacter.canceled -= instance.OnSwitchCharacter;
        }

        public void RemoveCallbacks(IIsometricActions instance)
        {
            if (m_Wrapper.m_IsometricActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IIsometricActions instance)
        {
            foreach (var item in m_Wrapper.m_IsometricActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_IsometricActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public IsometricActions @Isometric => new IsometricActions(this);
    public interface IFPVActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnSwitchCamera(InputAction.CallbackContext context);
        void OnOne(InputAction.CallbackContext context);
        void OnTwo(InputAction.CallbackContext context);
        void OnThree(InputAction.CallbackContext context);
        void OnFour(InputAction.CallbackContext context);
        void OnFive(InputAction.CallbackContext context);
        void OnSix(InputAction.CallbackContext context);
        void OnSeven(InputAction.CallbackContext context);
        void OnEight(InputAction.CallbackContext context);
        void OnNine(InputAction.CallbackContext context);
        void OnZero(InputAction.CallbackContext context);
        void OnSwitchCharacter(InputAction.CallbackContext context);
    }
    public interface ITopDownActions
    {
        void OnKeyboardCameraMovement(InputAction.CallbackContext context);
        void OnScreenEdgePanning(InputAction.CallbackContext context);
        void OnClickAndDrag(InputAction.CallbackContext context);
        void OnZoomCamera(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnSwitchCamera(InputAction.CallbackContext context);
        void OnOne(InputAction.CallbackContext context);
        void OnTwo(InputAction.CallbackContext context);
        void OnThree(InputAction.CallbackContext context);
        void OnFour(InputAction.CallbackContext context);
        void OnFive(InputAction.CallbackContext context);
        void OnSix(InputAction.CallbackContext context);
        void OnSeven(InputAction.CallbackContext context);
        void OnEight(InputAction.CallbackContext context);
        void OnNine(InputAction.CallbackContext context);
        void OnZero(InputAction.CallbackContext context);
        void OnSwitchCharacter(InputAction.CallbackContext context);
    }
    public interface IIsometricActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnMouse(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnSwitchCamera(InputAction.CallbackContext context);
        void OnOne(InputAction.CallbackContext context);
        void OnTwo(InputAction.CallbackContext context);
        void OnThree(InputAction.CallbackContext context);
        void OnFour(InputAction.CallbackContext context);
        void OnFive(InputAction.CallbackContext context);
        void OnSix(InputAction.CallbackContext context);
        void OnSeven(InputAction.CallbackContext context);
        void OnEight(InputAction.CallbackContext context);
        void OnNine(InputAction.CallbackContext context);
        void OnZero(InputAction.CallbackContext context);
        void OnSwitchCharacter(InputAction.CallbackContext context);
    }
}
